upstream servidores {
    server blue_app:3000;
    # server green_app:3000;
}

server {
    listen 80;
    
    location / {
        proxy_pass http://servidores;
        proxy_set_header Host $host;
    }
}